### PR TITLE
Implement cross compiles and uploads

### LINKED ISSUE #49: Build releases using taskcluster-github
When we create a new Github release of taskcluster-cli, tc-github should automatically build and upload binaries for the various platforms we support, and make them available for users.

### PR DESCRIPTION
**Pull request by t0xicCode**
This closes #49. 

gox does the cross-compilation, and _upload_release was modified to upload multiple binaries.

### CODE REVIEW

**Comment by t0xicCode** [comment]
Seems like golint is failing this PR, but nowhere near where I made changes.

**Comment by djmitche** [comment]
Yeah, I'm tired of golint's shenanigans.  I think it's time to disable it.

**Comment by t0xicCode** [comment]
I wonder why it had a problem on taskcluster but not on travis.

**Comment by djmitche** [comment]
Travis doesn't run golint, just the tests.

**Comment by djmitche** [comment]
Removal PR in #147.

**Pull request merged**
