### PR TITLE
Make lint checks actually pass, and easier to run

### PR DESCRIPTION
**Pull request by djmitche**
Just about every pull request since we have started running golint has has a big red X because golint found some lint problem in code the PR hadn't changed, but golint had not found that error in the last commit on master.  That means we're digging through logs to find out whether the red X is "real" or "fake", and we're tempted to ignore it.

I don't know why golint is doing this -- it's possible it's just under active development, and gometalinter is pulling in the latest, and that's adding new errors every few days.  At any rate, I think it's a net negative on development performance on this project.

### CODE REVIEW

**Comment by t0xicCode** [comment]
We should still recommend that contributors run it before pushing though.

**Comment by djmitche** [comment]
I'm not sure how we could fairly do that without running into the same issues, though.

**Comment by djmitche** [comment]
Hm, actually we (still?) don't have lint running on pushes to the master branch, so it's possible we just keep landing worse lint.

**Comment by djmitche** [comment]
..but when I run the gometalinter command from `.taskcluster.yml`, I get 715 errors, which is a LOT more than we've been seeing in pushes.

**Comment by t0xicCode** [comment]
Seems like all of the errors are due to `gotype`. Disabling that one seem to fix it running locally.

**Comment by djmitche** [comment]
Indeed!  I did some other refactoring, too.. update incoming..

**Comment by djmitche** [comment]
This is incredibly frustrating.  I ran gometalinter before that push, and it ran without errors.  Pushed, updated the PR, and ran again just for fun.  And
```
cmds/shell/cmd.go:85:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
cmds/shell/cmd.go:93:21:warning: error strings should not be capitalized or end with punctuation or a newline (golint)
```
It's correct about that issue, but if it's not going to detect the issue 100% of the time, it's no good to us.

**Comment by djmitche** [comment]
Oh, it didn't find it earlier because I'd removed `--enable=gometalinter` in that command line.  I shouldn't jump to conclusions :)

**Pull request merged**
