### PR TITLE
Added and improved package-level documentation

### PR DESCRIPTION
**Pull request by t0xicCode**

### CODE REVIEW

**Comment by djmitche** [comment]
Looks good at a glance from me, but I'll defer to @yannlandry for a deeper look

**Comment by t0xicCode** [comment]
@djmitche I just added @yannlandry because he was the suggestion, but a review from you is great!

**Comment by djmitche** [comment]
Looks like this failed some lint checks, though:
```
cmds/group/actors_test.go:118:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/actors_test.go:73:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/actors_test.go:84:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/actors_test.go:95:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/fetchers_test.go:116:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/fetchers_test.go:157:15:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/fetchers_test.go:168:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/fetchers_test.go:180:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/fetchers_test.go:193:14:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
cmds/task/fetchers_test.go:204:14:warning: should use buf2.String() instead of string(buf2.Bytes()) (S1030) (gosimple)
cmds/version/version_test.go:26:18:warning: should use buf.String() instead of string(buf.Bytes()) (S1030) (gosimple)
```
I assume those are new checks?

**Comment by t0xicCode** [comment]
Seems like it. I'll open a new pr to fix them.

**Pull request merged**
