### PR TITLE
[WIP] - tests for the fetcher commands

### PR DESCRIPTION
**Pull request by AyubMohamed**

### CODE REVIEW

**Comment by djmitche** [comment]
@lteigrob please merge if you are happy with this (once the gosimple issue is fixed)

**Comment by AyubMohamed** [comment]
@djmitche Yea, we should be able to factor out the redundant parts. Also I think @lteigrob is working on the `TestArtifactsCommand ` so maybe we can merge it after she's done that test?

**Comment by djmitche** [comment]
good plan

**Comment by lteigrob** [comment]
Yep, in progress!

**Pull request merged**
